// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5DtCMPQFcW2AQVSdcsBmYLhJOltCdRUg',
    appId: '1:632173026832:web:709db973bda4f5845d3495',
    messagingSenderId: '632173026832',
    projectId: 'grievanceapp-97fc5',
    authDomain: 'grievanceapp-97fc5.firebaseapp.com',
    storageBucket: 'grievanceapp-97fc5.firebasestorage.app',
    measurementId: 'G-7K99H2WYQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxq3zltHCpRtaGi_QcgF_eudsxwl8O4j8',
    appId: '1:632173026832:android:6b9e4f40121e8f425d3495',
    messagingSenderId: '632173026832',
    projectId: 'grievanceapp-97fc5',
    storageBucket: 'grievanceapp-97fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8u5fDbKKj7Xz5fz9K5b-wv-mhyZku1KY',
    appId: '1:632173026832:ios:1a83fc84b61786485d3495',
    messagingSenderId: '632173026832',
    projectId: 'grievanceapp-97fc5',
    storageBucket: 'grievanceapp-97fc5.firebasestorage.app',
    iosBundleId: 'com.example.grievanceRedressalSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8u5fDbKKj7Xz5fz9K5b-wv-mhyZku1KY',
    appId: '1:632173026832:ios:1a83fc84b61786485d3495',
    messagingSenderId: '632173026832',
    projectId: 'grievanceapp-97fc5',
    storageBucket: 'grievanceapp-97fc5.firebasestorage.app',
    iosBundleId: 'com.example.grievanceRedressalSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5DtCMPQFcW2AQVSdcsBmYLhJOltCdRUg',
    appId: '1:632173026832:web:bf3701f98740635b5d3495',
    messagingSenderId: '632173026832',
    projectId: 'grievanceapp-97fc5',
    authDomain: 'grievanceapp-97fc5.firebaseapp.com',
    storageBucket: 'grievanceapp-97fc5.firebasestorage.app',
    measurementId: 'G-GVWG52E196',
  );
}
